export const actionsTypes = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_DETAILS: 'FETCH_DETAILS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECT_PRODUCT: 'SELECT_PRODUCTS',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
};
